# site settings
title: CGR LAB
subtitle: "@ Hanyang University"
email: 
description:
baseurl: # the subpath of your site, e.g. /blog
url: https://cgrhyu.github.io # the base hostname & protocol for your site
author:
street_address: # hard-coded to footer.htm
city: # hard-coded to footer.htm
state: # hard-coded to footer.htm
zip_code: # hard-coded to footer.htm
country: # hard-coded to footer.htm
phone: # hard-coded to footer.htm

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 60

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
